name: 📝 Generate profile summary cards

on:
  schedule:
    - cron: '0 2 * * *'   # 23 h BRT
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/profile-summary-cards.yml

permissions:            # ← ADICIONE ISTO
  contents: write        # permite dar commit
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.6.0
        with:
          USERNAME: gustavolima973
          UTC_OFFSET: -3
          CARD_THEME: dracula
          ACCESS_TOKEN: ${{ secrets.PROFILE_CARDS_TOKEN }}    # ← TOKEN AQUI

      - name: Commit & push
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "github-actions[bot]"
          git add profile-summary-card-output
          git commit -m "chore: update profile summary cards" || echo "No changes"
          git push
